/* eslint-disable no-unused-vars */
const users = [
  ["ba-e", "bae.nekoweb.org", true],
  ["chimeridae", "chimera.pet", true],
  ["corvidaegalaxy", "crisis.city", true],
  ["Giiki", "giikis2.nekoweb.org", true],
  ["LelIllumina", "lel.nekoweb.org", true],
  ["maxpixels", "max.nekoweb.org", true],
  ["ramudaamemura", "yumeo.nekoweb.org", true],
  ["tepiloxtl", "tepiloxtl.net", true],
  ["abyssmaze", "eye.nekoweb.org", false],
  ["angelscrybIood", "fairyapple.nekoweb.org", false],
  ["blurrybleu", "bleu.nekoweb.org", false],
  ["CorelVulpix", "s1nez.nekoweb.org", false],
  ["cqrcin0", "cqrcin0.nekoweb.org", false],
  ["dimdendev", "dimden.dev", false],
  ["excelesia", "", false],
  ["flowerz-2005", "flowerz.nekoweb.org", false],
  ["four-caddit", "fourstar.nekoweb.org", false],
  ["frenzy9", "ironstar.nekoweb.org", false],
  ["garfieldhirou", "apfel.nekoweb.org", false],
  ["gerawrd_way", "captor.nekoweb.org", false],
  ["gremlin682", "gremlin.nekoweb.org", false],
  ["iamdeka", "iamdeka.nekoweb.org", false],
  ["julylmao", "july.lol", false],
  ["lakiitu", "doqmeat.com", false],
  ["microbenggu", "housepen.nekoweb.org", false],
  ["milkywaydotmoe", "milkyway.moe", false],
  ["pupfae", "gup.nekoweb.org", false],
  ["raidopaizer", "raidopaizer.nekoweb.org", false],
  ["thnlqd", "thinliquid.dev", false],
  ["trademarkhell", "trademarkhell.net", false],
  ["oikmo", "oikmo.nekoweb.org", false],
];
const devs = [
  ["LelIllumina", "lel.nekoweb.org"],
  ["tepiloxtl", "tepiloxtl.net"],
];
