name: Deploy to Nekoweb

on:
 push:
    branches:
      - main

jobs:
 deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Prepare build
        run: |
          rm -rf ./build
          mkdir -p ./build
          rsync -av --exclude='.*' --exclude='images/*.png' --exclude='neco-arcgodmode.cur' --exclude='./build/' ./ ./build
          ls
          ls ./build

      - name: Deploy to Nekoweb
        uses: mp-pinheiro/nekoweb-deploy@0.0.1
        with:
          API_KEY: ${{ secrets.NEKOWEB_API_KEY }}
          BUILD_DIR: './build'
          DEPLOY_DIR: '/githubaction'
          CLEANUP: 'False'