name: Deploy to Nekoweb

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare build
        run: |
            mkdir -p ./build
            CHANGED_FILES=$(git diff --name-only HEAD^ HEAD)
            for FILE in $CHANGED_FILES; do
              rsync -av --exclude=".*" $FILE ${{ github.workspace }} ./build
            done

      - name: Deploy to Nekoweb
        uses: mp-pinheiro/nekoweb-deploy@0.0.2
        with:
          API_KEY: ${{ secrets.NEKOWEB_API_KEY }}
          BUILD_DIR: './build'
          DEPLOY_DIR: '/githubaction'
          CLEANUP: 'False'