name: Deploy to Nekoweb

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: deploy2nekoweb
    steps:
      - name: Checkout repository
        uses: actions/checkout@main

      - name: Prepare build
        run: |
          mkdir -p ./build
          rsync -av --exclude='.*' --exclude='node_modules' --exclude='build' --exclude='package.json' --exclude='pnpm-lock.json' --exclude='eslint.config.mjs' ./ ./build

      - name: deploy2nekoweb
        uses: deploy2nekoweb/deploy2nekoweb@main
        with:
          nekoweb-api-key: ${{ secrets.NEKOWEB_API_KEY }}
          nekoweb-cookie: ${{ secrets.NEKOWEB_COOKIE }}
          nekoweb-folder: "dist/"
          directory: "./build"
