name: Deploy to Nekoweb

on:
 push:
    branches:
      - main

jobs:
 deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare build
        run: |
          rm -rf ./build
          mkdir -p ./build
          rsync -av --exclude='.*' --exclude='images/*' --exclude='neco-arcgodmode.cur' --exclude='neco-arclooking.cur' --exclude='./build/' ./ ./build
          ls ./build

      - name: Deploy to Nekoweb
        uses: mp-pinheiro/nekoweb-deploy@0.2.2
        with:
          API_KEY: ${{ secrets.NEKOWEB_API_KEY }}
          BUILD_DIR: './build'
          DEPLOY_DIR: '/'
          CLEANUP: 'False'
          DELAY: '1' 
          NEKOWEB_PAGENAME: 'lel'
          ENCRYPTION_KEY: ${{ secrets.NEKOWEB_ENCRYPTION_KEY }}