name: Deploy to Nekoweb

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Auto Minify
        uses: nizarmah/auto-minify@v3.0.0

      - name: auto commit the minified files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "bot: Add auto minified files"

      - name: Prepare build
        run: |
          mkdir -p ./build
          rsync -av --exclude='.*' --exclude='test' --exclude='build' ./ ./build

      - name: Deploy to Nekoweb
        uses: mp-pinheiro/nekoweb-deploy@0.2.4
        with:
          API_KEY: ${{ secrets.NEKOWEB_API_KEY }}
          BUILD_DIR: "./build"
          DEPLOY_DIR: "/"
          CLEANUP: "False"
          DELAY: "0.5"
          NEKOWEB_PAGENAME: "lel"
          ENCRYPTION_KEY: ${{ secrets.NEKOWEB_ENCRYPTION_KEY }}
